Description: >
  wjoe2046
  Deploy a Elastic Container Registry repository
Parameters:
  RepositoryName:
    Description: Name of the ECR Repository
    Type: String

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
